### ISSUE TITLE
Code Collaboration

### ISSUE THREAD

**Issue by KevinZonda** [iXORTech/MCDReforged-Remote#3]

**Comment by Cubik65536** [comment]
Yes, [Visual Studio Code Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack) can probably help us do this job better

**Comment by Cubik65536** [comment]
I will create a wiki documentary for coding collaboration, this issue remains open till I finish that wiki

**Comment by KevinZonda** [comment]
> Yes, [Visual Studio Code Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare-pack) can probably help us do this job better

I will appreciate that if you could open one session so that we can work together
